eclipse-platform/eclipse.platform.ua

org.eclipse.ua.releng/platformUa.setup

https://github.com/eclipse-platform/eclipse.platform.ua/issues/2

Update /org.eclipse.ua.releng/platformUa.setup to clone the Github URI

---

org.eclipse.help.webapp/pom.xml

Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/130

Build help.webapp wih jetty-jspc-maven-plugin 10.0.8

---

org.eclipse.help.ui/src/org/eclipse/help/ui/internal/browser/embedded/EmbeddedBrowser.java

Problem:
In the _Help > Help Contents_ window in the status bar, sometimes the progress bar is missed to be hidden, even after page loading is completed. Also, JavaScript requests can cause a (stale) progress bar to be shown.
This happens in both, the legacy Help UI, and more often in the  [_Modernized Eclipse Help UI prototype_](https://github.com/eclipse-platform/eclipse.platform.ua/blob/58e2060a6efc181f16cef9b1d7224460ac65cb2c/org.eclipse.help.webapp/m/README.md).
See also @iloveeclipse's [comment on the _Modernized Eclipse Help UI prototype_](https://git.eclipse.org/r/c/platform/eclipse.platform.ua/+/170090/5#message-758e82ce5ab8347b797a36a3b5b0e2b25c95a90e):
> One more bug need to be addressed: the status bar on the bottom never disappears after indexing or search is done

Help window: show progress bar in status bar only when loading a page

---

org.eclipse.help.webapp/m/index.js

Improve the modernized help UI prototype as follows (done as one change, since they are technically related, even if they are different items from the user's point of view):
1. Focus content frame on opening a new topic:
When opening a topic via TOC, by selecting a search result or by opening a non search bookmark, the content frame should be focused in order to be able to use the keyboard for scrolling (e.g. via the UP/DOWN keys).
2. When clicking on a search result, scroll to the first hit:
Opening a search result should automatically scroll to the first hit (which worked in the past only for results of the instant search, but not for results of a full search).
3. Opening a search bookmark should set the search field:
When opening a bookmark of a search, the search field should display …

Modernized help UI prototype: minor search and navigation improvements

---

infocenter-web/infocenter-app/pom.xml
infocenter-web/infocenter-product/pom.xml
infocenter-web/pom.xml
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/pom.xml
org.eclipse.help/pom.xml
org.eclipse.tips.feature/pom.xml
org.eclipse.ua.tests.doc/pom.xml
org.eclipse.ua.tests/pom.xml
org.eclipse.ui.cheatsheets/pom.xml
org.eclipse.ui.intro.quicklinks.examples/pom.xml
org.eclipse.ui.intro.solstice.examples/pom.xml
org.eclipse.ui.intro/pom.xml
pom.xml
tests-pom/pom.xml

Tracked in [eclipse.platform.releng.aggregator#290](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/290) and [eclipse.platform.releng.aggregator#291](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/291)
Need to wait to merge until after 4.24 Release

WIP: POM and product version changes for 4.25 release

---

org.eclipse.help.base/META-INF/MANIFEST.MF
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/313

Version bump for 4.25 stream

---

Jenkinsfile
org.eclipse.ua.tests/pom.xml

Prep work for
eclipse-platform/eclipse.platform.releng.aggregator#293

Run verification build with Java 17.

---

org.eclipse.help.webapp/pom.xml

Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/363

Build jsps with jetty-jspc-maven-plugin 10.0.11

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/forceQualifierUpdate.txt
org.eclipse.help.webapp/pom.xml

Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/368

Jetty update4.19

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/forceQualifierUpdate.txt
org.eclipse.help.webapp/pom.xml

Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/368

Jetty update4.15

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/forceQualifierUpdate.txt
org.eclipse.help.webapp/pom.xml

Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/368

Jetty update4.8

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/forceQualifierUpdate.txt
org.eclipse.help.webapp/pom.xml

Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/368

Jetty update4.7

---

infocenter-web/README.md

Fix git clone instructions in infocenter readme

---

infocenter-web/README.md
infocenter-web/infocenter-build.launch
infocenter-web/pom.xml

Steps dealing with aggregator repository could be skipped by just
passing -Pbuild-individual-bundles to maven.
Further enhancing
https://github.com/eclipse-platform/eclipse.platform.ua/issues/21

Simplify infocenter usage

---

org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/HelpWebappPlugin.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/data/BookmarksData.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/data/CssUtil.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/data/RequestData.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/data/WorkingSetData.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/data/WorkingSetManagerData.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/service/SearchStateService.java
org.eclipse.help.webapp/src/org/eclipse/help/webapp/AbstractButton.java
org.eclipse.help.webapp/src/org/eclipse/help/webapp/AbstractFrame.java

Done in order to cause rebuild of the bundle as previous pom only change
made it being replaced by comparator.

Use JLS modifiers order

---

org.eclipse.help.webapp/pom.xml
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/data/IconFinder.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/servlet/CookieUtil.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/servlet/EclipseConnector.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/servlet/FilterHTMLHeadAndBodyOutputStream.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/servlet/FilterHTMLHeadOutputStream.java
org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/servlet/LiveHelpServlet.java

As it breaks the help system entirely.
Second commit is due here to cause actual rebuild of the bundle as pom only changes cause comparator to replace it with baseline.

Revert using default package for precompiled jsp files

---

org.eclipse.help.webapp/pom.xml

Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/396

Update Jetty version in R4_23_maintenance branch to 10.0.11 #396

---

org.eclipse.tips.feature/forceQualifierUpdate.txt

Needed by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/440

Touch tips feature for GSon update 

---

infocenter-web/infocenter-app/pom.xml
infocenter-web/infocenter-product/pom.xml
infocenter-web/pom.xml
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/pom.xml
org.eclipse.help/pom.xml
org.eclipse.tips.feature/pom.xml
org.eclipse.ua.tests.doc/pom.xml
org.eclipse.ua.tests/pom.xml
org.eclipse.ui.cheatsheets/pom.xml
org.eclipse.ui.intro.quicklinks.examples/pom.xml
org.eclipse.ui.intro.solstice.examples/pom.xml
org.eclipse.ui.intro/pom.xml
pom.xml
tests-pom/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/514

Opening of 4 26 stream for development

---

org.eclipse.help.base/META-INF/MANIFEST.MF
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/540

Version bumps for 4.26 stream

---

pom.xml

https://github.com/eclipse-platform/eclipse.platform.releng/issues/113

Fix typo in scmURL

---

org.eclipse.ua.tests.doc/src/org/eclipse/ua/tests/doc/internal/linkchecker/ApiDocTest.java

Use wiring api instead of the old PlatformAdmin.

Fix ApiDocTest unexpected documented exported package issue

---

org.eclipse.ua.tests.doc/src/org/eclipse/ua/tests/doc/internal/linkchecker/ApiDocTest.java

Remove unused constant in ApiDocTest

---

infocenter-web/infocenter-app/pom.xml
infocenter-web/infocenter-product/pom.xml
infocenter-web/pom.xml
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/pom.xml
org.eclipse.help/pom.xml
org.eclipse.tips.feature/pom.xml
org.eclipse.ua.tests.doc/pom.xml
org.eclipse.ua.tests/pom.xml
org.eclipse.ui.cheatsheets/pom.xml
org.eclipse.ui.intro.quicklinks.examples/pom.xml
org.eclipse.ui.intro.solstice.examples/pom.xml
org.eclipse.ui.intro/pom.xml
pom.xml
tests-pom/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/712

POM and product version changes for 4.27 release

---

org.eclipse.help.base/META-INF/MANIFEST.MF
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/725

Version bumps for 4.27 stream

---

infocenter-web/infocenter-product/infocenter.product

Use newer plugin id

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF

See https://github.com/eclipse-platform/eclipse.platform.ua/issues/18

Add version range to org.eclipse.jdt.core.compiler.batch dependency

---

org.eclipse.tips.feature/forceQualifierUpdate.txt

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/791

Bump version to accommodate dependency updates

---

org.eclipse.ua.tests.doc/META-INF/MANIFEST.MF
org.eclipse.ua.tests.doc/pom.xml
org.eclipse.ua.tests.doc/src/org/eclipse/ua/tests/doc/internal/linkchecker/LinkTest.java

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/136

Possible workaround for errors while checking non-file URLs

---

infocenter-web/infocenter-app/pom.xml
infocenter-web/infocenter-product/pom.xml
infocenter-web/pom.xml
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/pom.xml
org.eclipse.help/pom.xml
org.eclipse.tips.feature/pom.xml
org.eclipse.ua.tests.doc/pom.xml
org.eclipse.ua.tests/pom.xml
org.eclipse.ui.cheatsheets/pom.xml
org.eclipse.ui.intro.quicklinks.examples/pom.xml
org.eclipse.ui.intro.solstice.examples/pom.xml
org.eclipse.ui.intro/pom.xml
pom.xml
tests-pom/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/916

Parent pom updates

---

org.eclipse.help.base/META-INF/MANIFEST.MF
org.eclipse.help.base/pom.xml

version bumps for 4.28 stream
for platform.common.ua repo
Fixes: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/917

version bumps for 4.28 stream

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF

Update Manifest Bundle version corresponding to pom > org.eclipse.help.webapp version.
@sravanlakkimsetti

Update Manifest Bundle version

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/forceQualifierUpdate.txt
org.eclipse.help.webapp/pom.xml

@sravanlakkimsetti @gireeshpunathil

Update to Jetty 9.4.51

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/forceQualifierUpdate.txt
org.eclipse.help.webapp/pom.xml

Update Jetty Version to 9.4.51
@sravanlakkimsetti @gireeshpunathil

Update Jetty Version

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/pom.xml

Refs: https://github.com/eclipse/jetty.project/security/advisories/GHSA-p26g-97m4-6q7c
/cc @sravanlakkimsetti @MohananRahul

meta: version bump for jetty: additional changes

---

org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/pom.xml

Refs: https://github.com/eclipse/jetty.project/security/advisories/GHSA-p26g-97m4-6q7c

meta: update jetty version

---

org.eclipse.help.base/src/org/eclipse/help/internal/search/SearchQuery.java
org.eclipse.help.base/src_demo/org/apache/lucene/demo/html/Tags.java

See https://github.com/eclipse-platform/eclipse.platform/issues/444

Fix for "Redundant specification of type arguments" error

---

infocenter-web/infocenter-app/pom.xml
infocenter-web/infocenter-product/pom.xml
infocenter-web/pom.xml
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/pom.xml
org.eclipse.help/pom.xml
org.eclipse.tips.feature/pom.xml
org.eclipse.ua.tests.doc/pom.xml
org.eclipse.ua.tests/pom.xml
org.eclipse.ui.cheatsheets/pom.xml
org.eclipse.ui.intro.quicklinks.examples/pom.xml
org.eclipse.ui.intro.solstice.examples/pom.xml
org.eclipse.ui.intro/pom.xml
pom.xml
tests-pom/pom.xml

Tracked by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1100

POM and product version changes for 4.29 release

---

org.eclipse.help.base/META-INF/MANIFEST.MF
org.eclipse.help.base/pom.xml
org.eclipse.help.webapp/META-INF/MANIFEST.MF
org.eclipse.help.webapp/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1125

Version bumps for 4.29 stream

---

org.eclipse.ui.intro/META-INF/MANIFEST.MF
org.eclipse.ui.intro/pom.xml
org.eclipse.ui.intro/src/org/eclipse/ui/internal/intro/impl/presentations/FormIntroPartImplementation.java

To avoid calculation on right side.

Use short-circuit logic

---

org.eclipse.help.base/src/org/eclipse/help/internal/base/BaseHelpSystem.java
org.eclipse.help/META-INF/MANIFEST.MF
org.eclipse.help/pom.xml
org.eclipse.help/src/org/eclipse/help/internal/HelpPlugin.java

see https://rules.sonarsource.com/java/RSPEC-2168

fix wrong double-checked locking

---

org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/servlet/InjectionFilter.java
org.eclipse.ua.tests/META-INF/MANIFEST.MF
org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/ContextMergeTest.java
org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/ContextTest.java
org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/IndexEntryTest.java
org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/TopicTest.java
org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/XHTMLEntityTest.java
org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/FilterTest.java
org.eclipse.ua.tests/pom.xml
org.eclipse.ui.cheatsheets/src/org/eclipse/ui/internal/cheatsheets/registry/CheatSheetRegistryReader.java
org.eclipse.ui.intro/src/org/eclipse/ui/intro/contentproviders/EclipseRSSViewer.java

Add missing "static" modifier for constants

---

org.eclipse.help.ui/META-INF/MANIFEST.MF
org.eclipse.help.ui/src/org/eclipse/help/ui/internal/views/EngineDescriptorManager.java
org.eclipse.ui.cheatsheets/src/org/eclipse/ui/internal/cheatsheets/CheatSheetPlugin.java
org.eclipse.ui.intro.universal/META-INF/MANIFEST.MF
org.eclipse.ui.intro.universal/src/org/eclipse/ui/internal/intro/universal/contentdetect/ContentDetectHelper.java
org.eclipse.ui.intro/src/org/eclipse/ui/internal/intro/impl/html/IntroHTMLGenerator.java

Doesn't try to fix anything. Just code and warnings reduced.

Use try-with-resource

---

org.eclipse.help.base/src/org/eclipse/help/internal/xhtml/DynamicXHTMLProcessor.java

DynamicXHTMLProcessor: fix caching of XMLProcessor

---

org.eclipse.ui.intro/src/org/eclipse/ui/internal/intro/impl/swt/PageStyleManager.java

Avoid String.toLowerCase() using equalsIgnoreCase

---

org.eclipse.help.ui/forceQualifierUpdate.txt
org.eclipse.help/forceQualifierUpdate.txt
org.eclipse.tips.core/META-INF/MANIFEST.MF
org.eclipse.tips.core/forceQualifierUpdate.txt
org.eclipse.tips.ide/forceQualifierUpdate.txt
org.eclipse.tips.json/forceQualifierUpdate.txt
org.eclipse.tips.ui/forceQualifierUpdate.txt
org.eclipse.ua.tests/forceQualifierUpdate.txt
org.eclipse.ui.cheatsheets/forceQualifierUpdate.txt
org.eclipse.ui.intro.quicklinks/forceQualifierUpdate.txt
org.eclipse.ui.intro.universal/forceQualifierUpdate.txt
org.eclipse.ui.intro/forceQualifierUpdate.txt

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1184

Touch bundles affected by the new ecj version

---

org.eclipse.tips.core/src/org/eclipse/tips/core/Tip.java
org.eclipse.tips.core/src/org/eclipse/tips/core/TipImage.java
org.eclipse.tips.core/src/org/eclipse/tips/core/TipProvider.java
org.eclipse.tips.core/src/org/eclipse/tips/core/internal/TipManager.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/IDETipManager.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/TipsPreferences.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/Tip1_Welcome.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/Tip2_StartingTips.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/Tip3_StartingTips.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/Tip6_ActionsTip.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/Tip7_Extend.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/TipsTipProvider.java
org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/TwitterTipProvider.java
org.eclipse.tips.tests/src/org/eclipse/tips/core/TestTipProvider.java
org.eclipse.tips.ui/META-INF/MANIFEST.MF
org.eclipse.tips.ui/src/org/eclipse/tips/ui/internal/DefaultTipManager.java
org.eclipse.tips.ui/src/org/eclipse/tips/ui/internal/Slider.java
org.eclipse.tips.ui/src/org/eclipse/tips/ui/internal/TipComposite.java
org.eclipse.tips.ui/src/org/eclipse/tips/ui/internal/util/ImageUtil.java
org.eclipse.ui.intro.quicklinks/src/org/eclipse/ui/intro/quicklinks/URLLabelProvider.java

Leverage parameterization of `ResourceDescriptor` made in https://github.com/eclipse-platform/eclipse.platform.ui/pull/838.

Code improvements, clean-ups and replacement of deprecated methods
