eclipse-platform/eclipse.platform.ua

infocenter-web/infocenter-app/pom.xml
It has one less CVE from dependencies compared to version 3.3.1 used
now.
https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-war-plugin/3.3.2
https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-war-plugin/3.3.1
=> Build infocenter-app with maven-war-plugin 3.3.2

org.eclipse.help.webapp/m/index.js
In the past, queries has been converted to lower case for performance
reasons (to need only a single request for multiple queries that differ
only in case). This has been done based on the false assumption that
this will have no effect to the search results. But in some cases,
converting the search string to lower case affects the results.
For example, "EvaluationResult.NOT_LOADED" vs.
"evaluationresult.not_loaded" (both without quotes) leads to
different search results (current number of hits in parentheses; please
note that the search term is converted to lower case when entered in the
search field of the modernized UI, but not when given as URL parameter #q=...):
https://help.eclipse.org/latest/index.jsp?tab=search&searchWord=EvaluationResult.NOT_LOADED (38)
vs. …
=> Modernized help UI prototype: do not convert search string to lower case

org.eclipse.help.webapp/pom.xml
Use that version of jetty-jspc-maven-plugin.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/187
=> Update to Jetty 10.0.9

org.eclipse.help.webapp/META-INF/MANIFEST.MF, org.eclipse.ua.tests/pom.xml
Jasper shipped embeds ancient version of ecj which doesn't support
targeting newer Java versions. As Eclipse is the author of ecj it makes
sense to include our own version which is the absolute latest one.
Removed workaround in tests explicitly adding jdt.core that is no longer
needed
Fixes https://github.com/eclipse-platform/eclipse.platform.ua/issues/18
=> Fix help webapp compiling JSPs when run on Java 17+

org.eclipse.help.webapp/META-INF/MANIFEST.MF, org.eclipse.ua.tests/pom.xml
Reverts eclipse-platform/eclipse.platform.ua#20 as it breaks I-build with:
```
15:37:05  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:validate-classpath (default-validate-classpath) on project org.eclipse.help.webapp: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:validate-classpath failed: org.osgi.framework.BundleException: Bundle org.eclipse.help.webapp cannot be resolved:org.eclipse.help.webapp [36]
15:37:05  [ERROR]   Unresolved requirement: Import-Package: org.eclipse.jdt.core.compiler
15:37:05  [ERROR]     -> Export-Package: org.eclipse.jdt.core.compiler; bundle-symbolic-name="org.eclipse.jdt.core"; bundle-version="3.30.100.qualifier"; version="0.0.0"
15:37:05  [ERROR] …
```
=> Revert "Fix help webapp compiling JSPs when run on Java 17+"

org.eclipse.help.webapp/pom.xml
JSPc is configured to put class files in
org.eclipse.help.internal.webapp.jsp package but in order for these
class files to be used the following config is needed:
```
<context-param>
<param-name>org.eclipse.jetty.servlet.jspPackagePrefix</param-name>
<param-value>com.acme</param-value>
</context-param>
```
as per https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-jspc-maven-plugin
.
As this is not set and rightfully so cause that would require every help
plugin shipping *.jsp files to compile into
org.eclipse.help.internal.webapp.jsp package at runtime Jetty recompiles
them into org.apache.jsp package and uses these classes.
Furthermore (Jetty 10
docs)[https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-jsp]
doesn't mention …
=> Make webapp use precompiled jsp files.

org.eclipse.help.webapp/m/index.js
When using the Modernized help UI prototype, on Windows, in the _Help_ window (_Help > Help Contents_) which uses the Internet Explorers, _Print topic..._ should print not only the first page, but all pages of the topic.
**Problem:**
In the Internet Explorer [`print()`](https://www.w3schools.com/jsref/met_win_print.asp) for an iframe prints only the first page when the focus is not set into the iframe.
=> Modernized help UI prototype: Fix "Print topic..." in Internet Explorer

org.eclipse.ui.cheatsheets/src/org/eclipse/ui/internal/cheatsheets/views/CheatSheetViewer.java, org.eclipse.ui.cheatsheets/src/org/eclipse/ui/internal/cheatsheets/views/ViewItem.java
Fixes Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=202691
The Copy action tried to always copy from the "current item" even when this was not the selected item.
The change checks for the first item with focus (which should be only one item) and executes the copy on that item.
=> Bug 202691 - [Cheatsheets] Edit->Copy and Ctrl+C do not copy selected text

org.eclipse.ua.tests/META-INF/MANIFEST.MF
org.eclipse.equinox.http.servlet needs this package but it is marked as
optional so probably not added to the test runtime dependencies.
See https://github.com/eclipse-platform/eclipse.platform.ua/issues/42
=> Add "import org.apache.commons.fileupload" to org.eclipse.ua.tests

org.eclipse.ua.tests.doc/META-INF/MANIFEST.MF, org.eclipse.ua.tests.doc/pom.xml
org.eclipse.equinox.http.servlet needs this package but it is marked as
optional so probably not added to the test runtime dependencies.
See https://github.com/eclipse-platform/eclipse.platform.ua/issues/42
=> Add "import org.apache.commons.fileupload" to org.eclipse.ua.tests.doc

org.eclipse.ua.tests.doc/META-INF/MANIFEST.MF, org.eclipse.ua.tests/META-INF/MANIFEST.MF
SDK help does NOT need this package (it is marked as optional) so we
don't need that either here. It was added before based on wrong
assumption that it's the test only requirement.
It turned out, it was a regression in equinox.
See https://github.com/eclipse-platform/eclipse.platform.ua/issues/42
and https://github.com/eclipse-equinox/equinox/issues/88
=> Remove "import org.apache.commons.fileupload" from org.eclipse.ua.tests*

org.eclipse.tips.ide/build.properties
=> Remove org.eclipse.pde.ds.lib/annotations.jar from extra classpath

org.eclipse.ua.tests/META-INF/MANIFEST.MF, org.eclipse.ua.tests/data/cheatsheet/other/ExtraLongContent.xml, org.eclipse.ua.tests/plugin.xml, org.eclipse.ua.tests/pom.xml, org.eclipse.ui.cheatsheets/META-INF/MANIFEST.MF, org.eclipse.ui.cheatsheets/pom.xml, org.eclipse.ui.cheatsheets/src/org/eclipse/ui/internal/cheatsheets/views/CheatSheetViewer.java
Fixes #49 
Cheat Sheets now advance to the top of the next step.
How to test:
Open the "Extra Long Content" Cheat Sheet and resize the view so that it only fits one step. Then click trought the cheat sheet
=> bugfix-#49 Cheat Sheets advance to the bottom of the next step

org.eclipse.help.webapp/META-INF/MANIFEST.MF
Add hard require on o.e.jdt.core for this to work as jasper version shipped is too old to support that.
Jasper includes in-jar copy of old version of jdt so this is not new dependency but rather overriding ancient version shipped. Fixes https://github.com/eclipse-platform/eclipse.platform.ua/issues/18
=> Fix JSP compilation on Java 17+

org.eclipse.help.webapp/META-INF/MANIFEST.MF
Switch required bundle to org.eclipse.jdt.core as
org.eclipse.jdt.core.compiler.batch is artificial one created by Ant during the build and thus Maven/Tycho can't resolve it.
Hoping that https://github.com/eclipse-platform/eclipse.platform.ua/issues/18 works with this one.
=> Yet another try to fix jsp compilation on Java 17+

org.eclipse.help.webapp/META-INF/MANIFEST.MF
With https://github.com/eclipse-jdt/eclipse.jdt.core/issues/181 compiler is extracted into its own bundle so help webapp can depend on it only without bringing the extra deps.
=> Switch help.webapp to use jdt.core.compiler.batch

org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/remote/TestServerManager.java, org.eclipse.ua.tests/pom.xml
Ensuring that both jasper (for JspC) and jdt.core.compiler.batch (for actual java compiler) are in the target platform is needed.
=> Fix running tests on Jenkins

org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/remote/GetContentUsingRemoteHelp.java
=> Use assertNotEquals instead of assertFalse(!a.equals(b))

org.eclipse.ua.tests.doc/pom.xml
As can be seen at
https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/master/109/console :
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.jdt.feature.group
3.19.0.v20230205-1800
[ERROR]   Missing requirement: org.eclipse.jdt 3.19.0.v20230204-1800
requires 'osgi.bundle; org.eclipse.ui.cheatsheets [3.2.0,4.0.0)' but it
could not be found
[ERROR]   Missing requirement: org.eclipse.jdt 3.19.0.v20230205-1800
requires 'osgi.bundle; org.eclipse.ui.cheatsheets [3.2.0,4.0.0)' but it
could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.jdt.feature.group
3.19.0.v20230204-1955 depends on: org.eclipse.equinox.p2.iu;
org.eclipse.jdt [3.19.0.v20230204-1800,3.19.0.v20230204-1800]
[ERROR]   Cannot satisfy dependency: …
```
=> Fix master build

org.eclipse.help.webapp/pom.xml
Refs: https://github.com/eclipse/jetty.project/security/advisories/GHSA-p26g-97m4-6q7c
/cc @sravanlakkimsetti
=> meta: update jetty version

org.eclipse.tips.examples/META-INF/MANIFEST.MF, org.eclipse.tips.ide/META-INF/MANIFEST.MF, org.eclipse.tips.ide/build.properties, org.eclipse.ui.intro.quicklinks/META-INF/MANIFEST.MF
- Use properly closed version range
- Remove unnecessary imports of org.osgi.service.component.annotations (they are only necessary at compile-time and Tycho adds them for compilation on the fly).
=> Clean-up OSGi package imports

org.eclipse.tips.ide/META-INF/MANIFEST.MF, org.eclipse.ui.intro/META-INF/MANIFEST.MF
- Always use closed version ranges [1.X,2) with a minor lower bound
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056
=> Improve OSGi metadata about dependency to javax.inject/annotations

org.eclipse.ui.intro/META-INF/MANIFEST.MF
It was removed in PR https://github.com/eclipse-platform/eclipse.platform.ua/pull/19 because it is transitively available, since o.e.core.expressions is reexported by o.e.help, which is rexported by o.e.help.base, which is required by o.e.ui.intro. But the requirement of o.e.ui.intro for o.e.help.base is only optional and therefore the help bundles can be absent, which leads to class-loading errors when loading classes from o.e.core.expressions.
Restoring the requirement for o.e.core.expressions fixes this problem.
Fixes https://github.com/eclipse-platform/eclipse.platform.ua/issues/122
=> Restore required bundle o.e.core.expressions of o.e.ui.intro

org.eclipse.ua.tests.doc/META-INF/MANIFEST.MF, org.eclipse.ua.tests.doc/pom.xml, org.eclipse.ua.tests.doc/src/org/eclipse/ua/tests/doc/internal/linkchecker/LinkTest.java
Don't hide exceptions on resolving, fail test with the first one (otherwise test fails later with obscure NP exceptions).
This should help to understand why test fails randomly, but does not fix the test yet.
See https://github.com/eclipse-platform/eclipse.platform.ua/issues/130
=> Random failures in LinkTest (#130)

org.eclipse.tips.tests/src/org/eclipse/tips/core/TipTest.java
=> org.eclipse.tips.core.TipTest.testEqualsObject() fails #140

org.eclipse.help.base/src/org/eclipse/help/internal/workingset/AdaptableTocsArray.java
Did use identity hashcode.
see https://rules.sonarsource.com/java/RSPEC-2116
=> AdaptableTocsArray: fix hashCode()

org.eclipse.help/src/org/eclipse/help/internal/HelpData.java
normally parse() will close stream but won't do it on exception.
=> HelpData: close stream after use

org.eclipse.tips.feature/feature.xml
The  org.eclipse.tips.json bundle allows a range:
Import-Package: com.google.gson;version="[2.8.6,3.0.0)"
https://github.com/eclipse-platform/eclipse.platform.releng/issues/230
=> Don't include a specific version of gson

org.eclipse.ua.tests.doc/src/org/eclipse/ua/tests/doc/internal/linkchecker/LinkTest.java
https://github.com/eclipse-platform/eclipse.platform.ua/issues/155
=> LinkTest: fix NPE due to concurrent use of TreeMap #155

org.eclipse.help.base/src/org/eclipse/help/internal/browser/BrowserLog.java
SimpleDateFormat.format(new Date());
returns same string as immutable and thread-safe
DateTimeFormatter.format(new Date().toInstant())
=> Avoid use of not thread-safe SimpleDateFormat
